// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: user.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	EnsName       string                 `protobuf:"bytes,3,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	UserType      string                 `protobuf:"bytes,6,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"` // 'b2c', 'b2b', 'admin'
	ProjectId     string                 `protobuf:"bytes,15,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectRole   string                 `protobuf:"bytes,16,opt,name=project_role,json=projectRole,proto3" json:"project_role,omitempty"`
	// Social identities
	TwitterId     string `protobuf:"bytes,7,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	TwitterHandle string `protobuf:"bytes,8,opt,name=twitter_handle,json=twitterHandle,proto3" json:"twitter_handle,omitempty"`
	DiscordId     string `protobuf:"bytes,9,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	DiscordHandle string `protobuf:"bytes,10,opt,name=discord_handle,json=discordHandle,proto3" json:"discord_handle,omitempty"`
	DiscordToken  string `protobuf:"bytes,11,opt,name=discord_token,json=discordToken,proto3" json:"discord_token,omitempty"`
	// Timestamps
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *User) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *User) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *User) GetProjectRole() string {
	if x != nil {
		return x.ProjectRole
	}
	return ""
}

func (x *User) GetTwitterId() string {
	if x != nil {
		return x.TwitterId
	}
	return ""
}

func (x *User) GetTwitterHandle() string {
	if x != nil {
		return x.TwitterHandle
	}
	return ""
}

func (x *User) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

func (x *User) GetDiscordHandle() string {
	if x != nil {
		return x.DiscordHandle
	}
	return ""
}

func (x *User) GetDiscordToken() string {
	if x != nil {
		return x.DiscordToken
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	EnsName       string                 `protobuf:"bytes,2,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	UserType      string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *CreateUserRequest) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CreateUserRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserByWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByWalletRequest) Reset() {
	*x = GetUserByWalletRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByWalletRequest) ProtoMessage() {}

func (x *GetUserByWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByWalletRequest.ProtoReflect.Descriptor instead.
func (*GetUserByWalletRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	TwitterId     string                 `protobuf:"bytes,4,opt,name=twitter_id,json=twitterId,proto3" json:"twitter_id,omitempty"`
	TwitterHandle string                 `protobuf:"bytes,5,opt,name=twitter_handle,json=twitterHandle,proto3" json:"twitter_handle,omitempty"`
	DiscordId     string                 `protobuf:"bytes,6,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
	DiscordHandle string                 `protobuf:"bytes,7,opt,name=discord_handle,json=discordHandle,proto3" json:"discord_handle,omitempty"`
	DiscordToken  string                 `protobuf:"bytes,8,opt,name=discord_token,json=discordToken,proto3" json:"discord_token,omitempty"`
	EnsName       string                 `protobuf:"bytes,9,opt,name=ens_name,json=ensName,proto3" json:"ens_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetTwitterId() string {
	if x != nil {
		return x.TwitterId
	}
	return ""
}

func (x *UpdateUserRequest) GetTwitterHandle() string {
	if x != nil {
		return x.TwitterHandle
	}
	return ""
}

func (x *UpdateUserRequest) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

func (x *UpdateUserRequest) GetDiscordHandle() string {
	if x != nil {
		return x.DiscordHandle
	}
	return ""
}

func (x *UpdateUserRequest) GetDiscordToken() string {
	if x != nil {
		return x.DiscordToken
	}
	return ""
}

func (x *UpdateUserRequest) GetEnsName() string {
	if x != nil {
		return x.EnsName
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x19\n" +
	"\bens_name\x18\x03 \x01(\tR\aensName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tuser_type\x18\x06 \x01(\tR\buserType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x0f \x01(\tR\tprojectId\x12!\n" +
	"\fproject_role\x18\x10 \x01(\tR\vprojectRole\x12\x1d\n" +
	"\n" +
	"twitter_id\x18\a \x01(\tR\ttwitterId\x12%\n" +
	"\x0etwitter_handle\x18\b \x01(\tR\rtwitterHandle\x12\x1d\n" +
	"\n" +
	"discord_id\x18\t \x01(\tR\tdiscordId\x12%\n" +
	"\x0ediscord_handle\x18\n" +
	" \x01(\tR\rdiscordHandle\x12#\n" +
	"\rdiscord_token\x18\v \x01(\tR\fdiscordToken\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tlast_seen\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xb4\x01\n" +
	"\x11CreateUserRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x19\n" +
	"\bens_name\x18\x02 \x01(\tR\aensName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x16GetUserByWalletRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"\xb1\x02\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"twitter_id\x18\x04 \x01(\tR\ttwitterId\x12%\n" +
	"\x0etwitter_handle\x18\x05 \x01(\tR\rtwitterHandle\x12\x1d\n" +
	"\n" +
	"discord_id\x18\x06 \x01(\tR\tdiscordId\x12%\n" +
	"\x0ediscord_handle\x18\a \x01(\tR\rdiscordHandle\x12#\n" +
	"\rdiscord_token\x18\b \x01(\tR\fdiscordToken\x12\x19\n" +
	"\bens_name\x18\t \x01(\tR\aensName\"1\n" +
	"\fUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.auth.v1.UserR\x04user2\x93\x02\n" +
	"\vUserService\x12?\n" +
	"\n" +
	"CreateUser\x12\x1a.auth.v1.CreateUserRequest\x1a\x15.auth.v1.UserResponse\x129\n" +
	"\aGetUser\x12\x17.auth.v1.GetUserRequest\x1a\x15.auth.v1.UserResponse\x12G\n" +
	"\rGetUserWallet\x12\x1f.auth.v1.GetUserByWalletRequest\x1a\x15.auth.v1.UserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x1a.auth.v1.UpdateUserRequest\x1a\x15.auth.v1.UserResponseB@Z>github.com/Launchkit-org/LaunchKit/shared/proto/auth/v1;authv1b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*User)(nil),                   // 0: auth.v1.User
	(*CreateUserRequest)(nil),      // 1: auth.v1.CreateUserRequest
	(*GetUserRequest)(nil),         // 2: auth.v1.GetUserRequest
	(*GetUserByWalletRequest)(nil), // 3: auth.v1.GetUserByWalletRequest
	(*UpdateUserRequest)(nil),      // 4: auth.v1.UpdateUserRequest
	(*UserResponse)(nil),           // 5: auth.v1.UserResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	6, // 0: auth.v1.User.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: auth.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	6, // 2: auth.v1.User.last_seen:type_name -> google.protobuf.Timestamp
	0, // 3: auth.v1.UserResponse.user:type_name -> auth.v1.User
	1, // 4: auth.v1.UserService.CreateUser:input_type -> auth.v1.CreateUserRequest
	2, // 5: auth.v1.UserService.GetUser:input_type -> auth.v1.GetUserRequest
	3, // 6: auth.v1.UserService.GetUserWallet:input_type -> auth.v1.GetUserByWalletRequest
	4, // 7: auth.v1.UserService.UpdateUser:input_type -> auth.v1.UpdateUserRequest
	5, // 8: auth.v1.UserService.CreateUser:output_type -> auth.v1.UserResponse
	5, // 9: auth.v1.UserService.GetUser:output_type -> auth.v1.UserResponse
	5, // 10: auth.v1.UserService.GetUserWallet:output_type -> auth.v1.UserResponse
	5, // 11: auth.v1.UserService.UpdateUser:output_type -> auth.v1.UserResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
